require "user.options"

require "user.autopairs"
require "user.cmp"
require "user.colorscheme"
require "user.comment"
require "user.git-blame"
require "user.gitsigns"
require "user.hop"
require "user.indentline"
require "user.keymaps"
require "user.lsp"
require "user.neogit"
require "user.nvim-tree"
require "user.bufferline" -- must come after user.options
require "user.plugins"
require "user.surround"
require "user.telescope"
require "user.treesitter"
require "user.whichkey"
