#!/bin/sh
# HISTFILE="$XDG_DATA_HOME"/zsh/history
HISTSIZE=1000000
SAVEHIST=1000000
export PATH="$HOME/.local/bin":$PATH
export PATH="/opt/homebrew/sbin:/opt/homebrew/bin:/usr/local/sbin:$PATH"
export MANPAGER='nvim +Man!'
export MANWIDTH=999
eval "$(zoxide init zsh)"
# eval "`pip completion --zsh`"
